---
# handlers file for install-apache-webserver

- name: for_Debian
  service: name=apache2 state=restarted
  when: ansible_os_family == "Debian"

- name: for_RedHat
  service: name=httpd state=restarted
  when: ansible_os_family == "RedHat"